### ISSUE TITLE
Error loading optional module com.google.android.gms.vision.face

### ISSUE THREAD

**Issue by sareban101** [gaetanozappi/Android-face-filters#7]
Hi
I have this error in onCreate:
Error loading optional module com.google.android.gms.vision.face
    gv: No acceptable module found. Local version is 0 and remote version is 0.
        at gy.d(:com.google.android.gms.dynamite_dynamitemodulesa@204516079@20.45.16 (120306-0):84)
        at com.google.android.gms.vision.face.ChimeraNativeFaceDetectorCreator.b(:com.google.android.gms.dynamite_dynamitemodulesa@204516079@20.45.16 (120306-0):2)
        at com.google.android.gms.vision.face.ChimeraNativeBaseFaceDetectorCreator.newFaceDetector(:com.google.android.gms.dynamite_dynamitemodulesa@204516079@20.45.16 (120306-0):4)
        at jw.u(:com.google.android.gms.dynamite_dynamitemodulesa@204516079@20.45.16 (120306-0):4)
        at ak.onTransact(:com.google.android.gms.dynamite_dynamitemodulesa@204516079@20.45.16 (120306-0):4)
        at android.os.Binder.transact(Binder.java:914)
        at com.google.android.gms.vision.face.internal.client.zzd$zza$zza.zza(Unknown Source:40)
        at com.google.android.gms.vision.face.internal.client.zzf.zzchx(Unknown Source:37)
        at com.google.android.gms.vision.face.internal.client.zzf.isOperational(Unknown Source:0)
        at com.google.android.gms.vision.face.internal.client.zzf.zzb(Unknown Source:0)
        at com.google.android.gms.vision.face.FaceDetector.detect(Unknown Source:19)
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:19)
        at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source:98)
        at java.lang.Thread.run(Thread.java:919)

In API 29 Sumsung A01

How can I fix it?
Please help me

**Comment by guixin567** [comment]
@sareban101 Hey, buddy, have you solved this problem yet
